CREATE TABLE CLOTHING(
    NAME VARCHAR(100) NOT NULL,
    CATEGORY VARCHAR(100) NOT NULL
);

INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('iSwim Summer Bikini', 'Bikinis');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('iWalk Blue Jeans', 'Trousers');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('iWalk Dress Trousers', 'Trousers');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('iWalk Long White Dress', 'Dresses');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('Nice Yellow Shirt', 'Tops');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('Nice Green T', 'Tops');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('iRun Black Trainers', 'Shoes');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('iRun White Trainers', 'Shoes');
INSERT INTO CLOTHING (NAME, CATEGORY) VALUES ('Elegant Handcrafted Clogs', 'Shoes');